import Head from 'next/head';
import { useContext } from 'react';
import UserRegistration from '../src/components/Register/RegisterUser';
import { Form } from '../src/context/FormContext';
import MainPage from './MainPage/index';


export default function Home() {
  const {signUp} = useContext(Form);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {signUp ? <MainPage />  : <UserRegistration />}
    </>
  )
}
